// =====================================================================
// PLANETARY BALL MILL FOR NANOPARTICLE SYNTHESIS
// Parametric 3D CAD Model with Mathematically Exact Gears & Cooling Fins
// Generated by NanoMill AI CAD Engine
// =====================================================================

$fn = 48; // Surface smoothness

// --- KINEMATIC & EXACT GEAR SIZING ---
R_sun = 160.00;              // Center distance (mm)
r_vial_inner = 45.0;      // Inner vial radius (mm)
h_vial = 90.0;            // Vial inner height (mm)
wall_th = 12.0;          // Vial shell thickness (mm)
r_vial_outer = r_vial_inner + wall_th;
h_vial_total = h_vial + 22.0;
num_vials = 4;            // Number of vials
gear_ratio_k = -2.00;     // Ratio omega / Omega

z_planet = 20;            // Planet gear teeth
z_sun = 40;                  // Sun gear teeth

// Exact pitch radii satisfying: r_sun_pitch + r_planet_pitch = R_sun
r_planet_pitch = 53.33;
r_sun_pitch = 106.67;
gear_module = 5.33;  // Common module for perfect meshing
gear_thick = 16.0;

// Mechanical Layout Elevations (mm)
base_z = -22.0;
gear_z = 0.0;                     // Common gear plane elevation
disc_z = gear_z + gear_thick + 4.0;
vial_z = disc_z + 18.0;

disc_radius = 235.0;
disc_thick = 18.0;
shaft_diam = 28.0;

// --- COLORS ---
color_steel = [0.90, 0.91, 0.93, 1.0];      // Light Satin Steel
color_gear_sun = [0.82, 0.65, 0.25, 1.0];   // Machined Bronze Sun Gear
color_gear_planet = [0.45, 0.50, 0.58, 1.0];// Alloy Steel Planet Gear
color_fin = [0.85, 0.88, 0.92, 1.0];        // Cooling Fin Aluminum
color_lid = [0.15, 0.45, 0.85, 1.0];        // Anodized Blue Clamp Lid
color_indicator = [0.95, 0.30, 0.15, 1.0];  // Rotational Indicator (Orange-Red)
color_ball = [0.95, 0.78, 0.25, 1.0];       // Grinding Media

// --- MAIN ASSEMBLY ---
module PlanetaryBallMillAssembly() {
    // 1. Base Housing & Motor Mount
    BaseMotorHousing();

    // 2. Stationary Central Sun Gear (Mounted at gear_z)
    translate([0, 0, gear_z])
        MechanicalSpurGear(r = r_sun_pitch, teeth = z_sun, thickness = gear_thick, bore = shaft_diam + 6, col = color_gear_sun);

    // 3. Central Drive Shaft & Sun Carrier Disc
    CentralCarrierUnit();

    // 4. Planetary Vials with meshing Planet Gears, Cooling Fins & Indicators
    for (i = [0 : num_vials - 1]) {
        angle = i * (360.0 / num_vials);
        rotate([0, 0, angle]) {
            // Planet Gear at exact coplanar gear_z meshing with sun gear
            translate([R_sun, 0, gear_z])
                rotate([0, 0, (180.0 / z_planet)])
                    MechanicalSpurGear(r = r_planet_pitch, teeth = z_planet, thickness = gear_thick, bore = 14, col = color_gear_planet);

            // Spindle shaft connecting gear through carrier disc
            translate([R_sun, 0, gear_z])
                cylinder(r = 7.0, h = vial_z - gear_z);

            // Milling Vial on top of carrier disc
            translate([R_sun, 0, vial_z])
                PlanetaryVialUnit();
        }
    }
}

// --- MODULE: Spur Gear with True Involute-Like Trapezoidal Teeth ---
module MechanicalSpurGear(r, teeth, thickness, bore, col) {
    color(col) {
        difference() {
            union() {
                // Base cylinder
                cylinder(r = r - gear_module * 1.0, h = thickness);
                // Involute-like teeth
                tooth_angle = 360.0 / teeth;
                for (t = [0 : teeth - 1]) {
                    rotate([0, 0, t * tooth_angle])
                        translate([r - gear_module * 0.9, -gear_module * 0.65, 0])
                            cube([gear_module * 1.7, gear_module * 1.3, thickness]);
                }
            }
            // Shaft bore
            translate([0, 0, -1])
                cylinder(r = bore / 2, h = thickness + 2);
        }
    }
}

// --- MODULE: Central Carrier Unit ---
module CentralCarrierUnit() {
    color(color_steel) {
        // Carrier Disc sitting directly above the gears
        translate([0, 0, disc_z])
            difference() {
                cylinder(r = disc_radius, h = disc_thick);
                // Center bore
                translate([0, 0, -1])
                    cylinder(r = shaft_diam / 2, h = disc_thick + 2);
                // Bearing recesses for vial spindles
                for (i = [0 : num_vials - 1]) {
                    rotate([0, 0, i * (360.0 / num_vials)])
                        translate([R_sun, 0, -1])
                            cylinder(r = 16, h = disc_thick + 2);
                }
            }

        // Central Motor Drive Shaft
        translate([0, 0, gear_z])
            cylinder(r = shaft_diam / 2, h = vial_z + 30);
    }

    // Motor Shaft Rotation Direction Indicator (Omega Arrow)
    color(color_indicator) {
        translate([0, 0, vial_z + 30]) {
            cylinder(r = 12, h = 4);
            translate([8, 0, 2])
                rotate([0, 0, -90])
                    cylinder(r1 = 7, r2 = 1, h = 4, $fn = 3);
        }
    }
}

// --- MODULE: Planetary Milling Vial with Cooling Fins & Indicator ---
module PlanetaryVialUnit() {
    // Hollow Vial Body
    color(color_steel) {
        difference() {
            cylinder(r = r_vial_outer, h = h_vial_total - 16);
            translate([0, 0, 10])
                cylinder(r = r_vial_inner, h = h_vial_total);
        }
    }

    // Annular Cooling Fins (5 ribs)
    color(color_fin) {
        for (f = [0 : 4]) {
            translate([0, 0, 18 + f * 14])
                difference() {
                    cylinder(r = r_vial_outer + 8.0, h = 2.5);
                    translate([0, 0, -1])
                        cylinder(r = r_vial_outer - 0.5, h = 4.5);
                }
        }
    }

    // Sealed Clamp Lid
    color(color_lid) {
        translate([0, 0, h_vial_total - 16]) {
            cylinder(r = r_vial_outer + 3, h = 16);
            translate([0, 0, 16])
                cylinder(r = 16, h = 10);
        }
    }

    // Rotational Direction Indicator Arrow on Lid (Shows Jar Spin w)
    color(color_indicator) {
        translate([0, 0, h_vial_total + 10]) {
            cube([r_vial_outer * 1.5, 5, 3], center = true);
            translate([r_vial_outer * 0.75, 0, 0])
                rotate([0, 0, -90])
                    cylinder(r1 = 8, r2 = 1, h = 3, $fn = 3);
        }
    }

    // Grinding Media inside
    color(color_ball) {
        translate([12, 10, 22]) sphere(r = 5);
        translate([-14, -8, 26]) sphere(r = 5);
        translate([6, -14, 30]) sphere(r = 5);
        translate([-8, 12, 34]) sphere(r = 5);
    }
}

// --- MODULE: Base Housing ---
module BaseMotorHousing() {
    color([0.80, 0.82, 0.86]) {
        translate([0, 0, base_z])
            difference() {
                cylinder(r = disc_radius + 15, h = abs(base_z));
                translate([0, 0, 2])
                    cylinder(r = disc_radius - 10, h = abs(base_z));
            }
    }
}

// Instantiate
PlanetaryBallMillAssembly();
