"""
CAD and 3D Model Generator for Planetary Ball Mill.
Generates:
1. OpenSCAD code (.scad) - Universal standard for AI-driven 3D CAD modeling with mathematically exact gears, cooling fins, and indicators.
2. Direct 3D STL / OBJ meshes using pure Python with exact gear sizing, cooling fins, and indicators.
3. Self-contained interactive 3D WebGL/HTML viewports in LIGHT MODE with:
   - Mathematically exact planetary gear pitch radii satisfying r_sun + r_planet = R_sun.
   - Perfectly coplanar gear elevation so sun and planet gears mesh side-by-side.
   - Live gear rebuilding on ratio change (k = -1.0, -1.5, -2.0, -2.5, -3.0).
   - Assembly Hierarchy Tree (Left Panel) with part visibility checkboxes.
   - Spindle RPM & Telemetry Monitor (Right Panel) tracking each individual jar.
"""

import numpy as np
import os
from typing import Dict, Any, List
from .kinematics import PlanetaryKinematics, MillGeometry, PlanetaryGears


class BallMillCADGenerator:
    """
    Parametric 3D Model Generator for Planetary Ball Mill with exact mechanical gear meshing,
    annular cooling fins, rotational indicators, and interactive telemetry.
    """

    def __init__(self, kinematics: PlanetaryKinematics):
        self.kin = kinematics
        self.geom = kinematics.geom
        self.gears = getattr(kinematics, "gears", PlanetaryGears.from_ratio(kinematics.gear_ratio_k))

    def generate_openscad_code(self) -> str:
        """
        Generates parametric OpenSCAD source code with mathematically exact gear teeth,
        coplanar pitch circles satisfying r_sun + r_planet = R_sun, cooling fins, and indicators.
        """
        R_sun = self.geom.sun_radius_m * 1000.0       # mm
        r_vial = self.geom.vial_radius_m * 1000.0     # mm
        h_vial = self.geom.vial_height_m * 1000.0     # mm
        n_vials = self.geom.num_vials
        wall_th = 12.0                                # mm
        disc_thick = 18.0                             # mm
        disc_radius = R_sun + r_vial + 30.0           # mm
        k_ratio = self.kin.gear_ratio_k

        # Exact gear kinematics
        z_planet = 20
        z_sun = int(round(abs(k_ratio) * z_planet))
        r_planet_pitch = R_sun * (z_planet / (z_sun + z_planet))
        r_sun_pitch = R_sun * (z_sun / (z_sun + z_planet))
        gear_module = (2.0 * R_sun) / (z_sun + z_planet)

        scad_code = f"""// =====================================================================
// PLANETARY BALL MILL FOR NANOPARTICLE SYNTHESIS
// Parametric 3D CAD Model with Mathematically Exact Gears & Cooling Fins
// Generated by NanoMill AI CAD Engine
// =====================================================================

$fn = 48; // Surface smoothness

// --- KINEMATIC & EXACT GEAR SIZING ---
R_sun = {R_sun:.2f};              // Center distance (mm)
r_vial_inner = {r_vial:.1f};      // Inner vial radius (mm)
h_vial = {h_vial:.1f};            // Vial inner height (mm)
wall_th = {wall_th:.1f};          // Vial shell thickness (mm)
r_vial_outer = r_vial_inner + wall_th;
h_vial_total = h_vial + 22.0;
num_vials = {n_vials};            // Number of vials
gear_ratio_k = {k_ratio:.2f};     // Ratio omega / Omega

z_planet = {z_planet};            // Planet gear teeth
z_sun = {z_sun};                  // Sun gear teeth

// Exact pitch radii satisfying: r_sun_pitch + r_planet_pitch = R_sun
r_planet_pitch = {r_planet_pitch:.2f};
r_sun_pitch = {r_sun_pitch:.2f};
gear_module = {gear_module:.2f};  // Common module for perfect meshing
gear_thick = 16.0;

// Mechanical Layout Elevations (mm)
base_z = -22.0;
gear_z = 0.0;                     // Common gear plane elevation
disc_z = gear_z + gear_thick + 4.0;
vial_z = disc_z + {disc_thick:.1f};

disc_radius = {disc_radius:.1f};
disc_thick = {disc_thick:.1f};
shaft_diam = 28.0;

// --- COLORS ---
color_steel = [0.90, 0.91, 0.93, 1.0];      // Light Satin Steel
color_gear_sun = [0.82, 0.65, 0.25, 1.0];   // Machined Bronze Sun Gear
color_gear_planet = [0.45, 0.50, 0.58, 1.0];// Alloy Steel Planet Gear
color_fin = [0.85, 0.88, 0.92, 1.0];        // Cooling Fin Aluminum
color_lid = [0.15, 0.45, 0.85, 1.0];        // Anodized Blue Clamp Lid
color_indicator = [0.95, 0.30, 0.15, 1.0];  // Rotational Indicator (Orange-Red)
color_ball = [0.95, 0.78, 0.25, 1.0];       // Grinding Media

// --- MAIN ASSEMBLY ---
module PlanetaryBallMillAssembly() {{
    // 1. Base Housing & Motor Mount
    BaseMotorHousing();

    // 2. Stationary Central Sun Gear (Mounted at gear_z)
    translate([0, 0, gear_z])
        MechanicalSpurGear(r = r_sun_pitch, teeth = z_sun, thickness = gear_thick, bore = shaft_diam + 6, col = color_gear_sun);

    // 3. Central Drive Shaft & Sun Carrier Disc
    CentralCarrierUnit();

    // 4. Planetary Vials with meshing Planet Gears, Cooling Fins & Indicators
    for (i = [0 : num_vials - 1]) {{
        angle = i * (360.0 / num_vials);
        rotate([0, 0, angle]) {{
            // Planet Gear at exact coplanar gear_z meshing with sun gear
            translate([R_sun, 0, gear_z])
                rotate([0, 0, (180.0 / z_planet)])
                    MechanicalSpurGear(r = r_planet_pitch, teeth = z_planet, thickness = gear_thick, bore = 14, col = color_gear_planet);

            // Spindle shaft connecting gear through carrier disc
            translate([R_sun, 0, gear_z])
                cylinder(r = 7.0, h = vial_z - gear_z);

            // Milling Vial on top of carrier disc
            translate([R_sun, 0, vial_z])
                PlanetaryVialUnit();
        }}
    }}
}}

// --- MODULE: Spur Gear with True Involute-Like Trapezoidal Teeth ---
module MechanicalSpurGear(r, teeth, thickness, bore, col) {{
    color(col) {{
        difference() {{
            union() {{
                // Base cylinder
                cylinder(r = r - gear_module * 1.0, h = thickness);
                // Involute-like teeth
                tooth_angle = 360.0 / teeth;
                for (t = [0 : teeth - 1]) {{
                    rotate([0, 0, t * tooth_angle])
                        translate([r - gear_module * 0.9, -gear_module * 0.65, 0])
                            cube([gear_module * 1.7, gear_module * 1.3, thickness]);
                }}
            }}
            // Shaft bore
            translate([0, 0, -1])
                cylinder(r = bore / 2, h = thickness + 2);
        }}
    }}
}}

// --- MODULE: Central Carrier Unit ---
module CentralCarrierUnit() {{
    color(color_steel) {{
        // Carrier Disc sitting directly above the gears
        translate([0, 0, disc_z])
            difference() {{
                cylinder(r = disc_radius, h = disc_thick);
                // Center bore
                translate([0, 0, -1])
                    cylinder(r = shaft_diam / 2, h = disc_thick + 2);
                // Bearing recesses for vial spindles
                for (i = [0 : num_vials - 1]) {{
                    rotate([0, 0, i * (360.0 / num_vials)])
                        translate([R_sun, 0, -1])
                            cylinder(r = 16, h = disc_thick + 2);
                }}
            }}

        // Central Motor Drive Shaft
        translate([0, 0, gear_z])
            cylinder(r = shaft_diam / 2, h = vial_z + 30);
    }}

    // Motor Shaft Rotation Direction Indicator (Omega Arrow)
    color(color_indicator) {{
        translate([0, 0, vial_z + 30]) {{
            cylinder(r = 12, h = 4);
            translate([8, 0, 2])
                rotate([0, 0, -90])
                    cylinder(r1 = 7, r2 = 1, h = 4, $fn = 3);
        }}
    }}
}}

// --- MODULE: Planetary Milling Vial with Cooling Fins & Indicator ---
module PlanetaryVialUnit() {{
    // Hollow Vial Body
    color(color_steel) {{
        difference() {{
            cylinder(r = r_vial_outer, h = h_vial_total - 16);
            translate([0, 0, 10])
                cylinder(r = r_vial_inner, h = h_vial_total);
        }}
    }}

    // Annular Cooling Fins (5 ribs)
    color(color_fin) {{
        for (f = [0 : 4]) {{
            translate([0, 0, 18 + f * 14])
                difference() {{
                    cylinder(r = r_vial_outer + 8.0, h = 2.5);
                    translate([0, 0, -1])
                        cylinder(r = r_vial_outer - 0.5, h = 4.5);
                }}
        }}
    }}

    // Sealed Clamp Lid
    color(color_lid) {{
        translate([0, 0, h_vial_total - 16]) {{
            cylinder(r = r_vial_outer + 3, h = 16);
            translate([0, 0, 16])
                cylinder(r = 16, h = 10);
        }}
    }}

    // Rotational Direction Indicator Arrow on Lid (Shows Jar Spin w)
    color(color_indicator) {{
        translate([0, 0, h_vial_total + 10]) {{
            cube([r_vial_outer * 1.5, 5, 3], center = true);
            translate([r_vial_outer * 0.75, 0, 0])
                rotate([0, 0, -90])
                    cylinder(r1 = 8, r2 = 1, h = 3, $fn = 3);
        }}
    }}

    // Red G-Force Vector Arrow (Shows instantaneous direction of G-Force / Ball Movement)
    color([0.94, 0.20, 0.20, 1.0]) {{
        translate([r_vial_outer * 0.1, 0, h_vial_total / 2])
            rotate([0, 90, 0]) {{
                cylinder(r = 3.2, h = r_vial_outer * 1.35);
                translate([0, 0, r_vial_outer * 1.35])
                    cylinder(r1 = 6.8, r2 = 0.5, h = 12.0);
            }}
    }}

    // Dynamic Ball Charge Bed clustered at Outward Wall (Gravitational Point)
    color(color_ball) {{
        translate([r_vial_inner - 10, 0, 16]) sphere(r = 6.5);
        translate([r_vial_inner - 12, 10, 18]) sphere(r = 6);
        translate([r_vial_inner - 12, -10, 18]) sphere(r = 6);
        translate([r_vial_inner - 14, 0, 30]) sphere(r = 5.5);
        translate([r_vial_inner - 16, 8, 28]) sphere(r = 5.5);
    }}
}}

// --- MODULE: Base Housing ---
module BaseMotorHousing() {{
    color([0.80, 0.82, 0.86]) {{
        translate([0, 0, base_z])
            difference() {{
                cylinder(r = disc_radius + 15, h = abs(base_z));
                translate([0, 0, 2])
                    cylinder(r = disc_radius - 10, h = abs(base_z));
            }}
    }}
}}

// Instantiate
PlanetaryBallMillAssembly();
"""
        return scad_code

    def export_openscad_file(self, filepath: str) -> str:
        """Saves the OpenSCAD file to disk."""
        code = self.generate_openscad_code()
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(code)
        return filepath

    def generate_pure_stl_mesh(self) -> bytes:
        """
        Generates a valid binary STL mesh directly in pure Python with exact gear sizing,
        coplanar gear heights, cooling fins, and indicators.
        """
        R_sun = self.geom.sun_radius_m * 1000.0
        r_vial = self.geom.vial_radius_m * 1000.0
        h_vial = self.geom.vial_height_m * 1000.0
        n_vials = self.geom.num_vials
        k_abs = abs(self.kin.gear_ratio_k)

        # Exact gear kinematics
        z_planet = 20
        z_sun = int(round(k_abs * z_planet))
        r_planet_pitch = R_sun * (z_planet / (z_sun + z_planet))
        r_sun_pitch = R_sun * (z_sun / (z_sun + z_planet))

        gear_z = 0.0
        gear_h = 16.0
        disc_z = gear_z + gear_h + 4.0
        disc_h = 18.0
        vial_base_z = disc_z + disc_h
        disc_r = R_sun + r_vial + 30.0

        triangles = []

        def add_cylinder(cx, cy, cz, r, h, segments=24):
            theta = np.linspace(0, 2 * np.pi, segments, endpoint=False)
            top_z = cz + h
            bot_z = cz
            for i in range(segments):
                i_next = (i + 1) % segments
                x1, y1 = cx + r * np.cos(theta[i]), cy + r * np.sin(theta[i])
                x2, y2 = cx + r * np.cos(theta[i_next]), cy + r * np.sin(theta[i_next])

                triangles.append(((x1, y1, bot_z), (x2, y2, bot_z), (x2, y2, top_z)))
                triangles.append(((x1, y1, bot_z), (x2, y2, top_z), (x1, y1, top_z)))
                triangles.append(((cx, cy, top_z), (x1, y1, top_z), (x2, y2, top_z)))
                triangles.append(((cx, cy, bot_z), (x2, y2, bot_z), (x1, y1, bot_z)))

        def add_box(cx, cy, cz, dx, dy, dz):
            x0, x1 = cx - dx / 2, cx + dx / 2
            y0, y1 = cy - dy / 2, cy + dy / 2
            z0, z1 = cz, cz + dz
            faces = [
                ((x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0)),
                ((x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)),
                ((x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1)),
                ((x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)),
                ((x0, y0, z0), (x0, y1, z0), (x0, y1, z1), (x0, y0, z1)),
                ((x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1)),
            ]
            for p0, p1, p2, p3 in faces:
                triangles.append((p0, p1, p2))
                triangles.append((p0, p2, p3))

        # 1. Base Housing
        add_cylinder(0, 0, -22.0, disc_r + 15.0, 22.0, segments=36)

        # 2. Central Sun Gear (Coplanar with planet gears at gear_z)
        add_cylinder(0, 0, gear_z, r_sun_pitch, gear_h, segments=36)

        # 3. Sun Carrier Disc (Sits above gears)
        add_cylinder(0, 0, disc_z, disc_r, disc_h, segments=36)

        # 4. Planetary Vials, Planet Gears, and Cooling Fins
        for v in range(n_vials):
            angle = v * (2.0 * np.pi / n_vials)
            vx = R_sun * np.cos(angle)
            vy = R_sun * np.sin(angle)

            # Planet Gear at exact coplanar gear_z
            add_cylinder(vx, vy, gear_z, r_planet_pitch, gear_h, segments=24)

            # Spindle shaft connecting gear to vial
            add_cylinder(vx, vy, gear_z, 7.0, vial_base_z - gear_z, segments=16)

            # Vial cylinder sitting on carrier disc
            add_cylinder(vx, vy, vial_base_z, r_vial + 10.0, h_vial + 15.0, segments=24)

            # Annular Cooling Fins (5 rings)
            for f in range(5):
                fin_z = vial_base_z + 18.0 + f * 14.0
                add_cylinder(vx, vy, fin_z, r_vial + 18.0, 3.0, segments=24)

            # Vial clamp lid
            lid_z = vial_base_z + h_vial + 15.0
            add_cylinder(vx, vy, lid_z, r_vial + 13.0, 14.0, segments=24)

            # Indicator pointer bar on top of jar
            add_box(vx, vy, lid_z + 14.0, (r_vial + 10.0) * 1.5, 6.0, 4.0)

        # 5. Central Motor Shaft & Indicator
        add_cylinder(0, 0, disc_z, 14.0, 40.0, segments=20)
        add_box(0, 0, disc_z + 40.0, 34.0, 8.0, 4.0)

        # Build binary STL
        header = b"NanoMill Planetary Ball Mill (Exact Gear Meshing & Fins)".ljust(80, b"\0")
        num_tris = len(triangles)
        record_list = [header, np.uint32(num_tris).tobytes()]

        for tri in triangles:
            p1, p2, p3 = np.array(tri[0]), np.array(tri[1]), np.array(tri[2])
            normal = np.cross(p2 - p1, p3 - p1)
            norm_mag = np.linalg.norm(normal)
            normal = normal / norm_mag if norm_mag > 1e-6 else np.array([0.0, 0.0, 1.0])

            record = np.array(
                [
                    normal[0], normal[1], normal[2],
                    p1[0], p1[1], p1[2],
                    p2[0], p2[1], p2[2],
                    p3[0], p3[1], p3[2],
                ],
                dtype=np.float32,
            ).tobytes() + b"\0\0"
            record_list.append(record)

        return b"".join(record_list)

    def export_stl_file(self, filepath: str) -> str:
        """Saves binary STL file to disk."""
        data = self.generate_pure_stl_mesh()
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        with open(filepath, "wb") as f:
            f.write(data)
        return filepath

    def generate_interactive_html(self, width: str = "100%", height: str = "640px") -> str:
        """
        Generates a standalone, fully self-contained WebGL 3D interactive viewer using Three.js in LIGHT MODE.
        Key Fixes & Features:
        - Mathematically exact planetary gear pitch radii satisfying: r_sun + r_planet = R_sun.
        - Exactly coplanar gear elevation so Sun Gear and Planet Gears mesh side-by-side.
        - Dynamic gear rebuilding on ratio testing (k = -1.0, -1.5, -2.0, -2.5, -3.0).
        - Model Hierarchy Tree (Left Panel) with individual visibility checkboxes.
        - Spindle RPM & Telemetry Monitor (Right Panel) tracking each jar's exact speed and dynamics.
        - Annular Cooling Fins on each vial.
        - Directional Rotational Indicators on central shaft and jar lids.
        """
        R_sun = self.geom.sun_radius_m * 100.0  # scaled units
        r_vial = self.geom.vial_radius_m * 100.0
        h_vial = self.geom.vial_height_m * 100.0
        n_vials = self.geom.num_vials
        k_init = self.kin.gear_ratio_k
        sun_rpm_init = self.kin.sun_rpm

        html_template = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0; overflow: hidden; background: #f8fafc;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #0f172a;
    }}
    #viewport-container {{ width: {width}; height: {height}; position: relative; overflow: hidden; }}
    #canvas-3d {{ width: 100%; height: 100%; display: block; }}
    
    /* Common Panel Styling (Light Studio Glassmorphism) */
    .cad-panel {{
      position: absolute; top: 12px; bottom: 12px; z-index: 10;
      background: rgba(255, 255, 255, 0.94); backdrop-filter: blur(10px);
      border: 1px solid #cbd5e1; border-radius: 12px;
      box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.08);
      display: flex; flex-direction: column;
      overflow: hidden; transition: transform 0.25s ease, opacity 0.2s ease;
    }}
    .panel-header {{
      padding: 12px 14px; background: #f1f5f9; border-bottom: 1px solid #e2e8f0;
      display: flex; justify-content: space-between; align-items: center;
      font-size: 13px; font-weight: 700; color: #0f172a;
    }}
    .panel-body {{
      padding: 12px 14px; overflow-y: auto; flex: 1; font-size: 12px;
    }}

    /* Left Panel: Assembly Hierarchy Tree */
    #left-hierarchy-panel {{
      left: 12px; width: 280px;
    }}
    #left-hierarchy-panel.collapsed {{
      transform: translateX(-295px);
    }}
    .tree-node {{
      margin-bottom: 4px; user-select: none;
    }}
    .tree-row {{
      display: flex; align-items: center; gap: 6px; padding: 4px 6px; border-radius: 6px;
      cursor: pointer; transition: background 0.15s; font-size: 11.5px; color: #1e293b;
    }}
    .tree-row:hover {{ background: #e2e8f0; }}
    .tree-indent {{ margin-left: 16px; border-left: 1px dashed #cbd5e1; padding-left: 6px; }}
    .tree-checkbox {{
      width: 14px; height: 14px; accent-color: #2563eb; cursor: pointer; margin: 0;
    }}
    .node-icon {{ font-size: 12px; }}

    /* Right Panel: RPM Control & Per-Jar Telemetry */
    #right-telemetry-panel {{
      right: 12px; width: 330px;
    }}
    #right-telemetry-panel.collapsed {{
      transform: translateX(345px);
    }}
    
    /* Panel Toggle Buttons */
    .panel-toggle-btn {{
      position: absolute; top: 12px; z-index: 12;
      background: #ffffff; border: 1px solid #cbd5e1; border-radius: 8px;
      padding: 6px 10px; font-size: 12px; font-weight: 700; color: #334155;
      cursor: pointer; box-shadow: 0 2px 6px rgba(0,0,0,0.06);
    }}
    .panel-toggle-btn:hover {{ background: #f8fafc; color: #0f172a; }}
    #btn-toggle-left {{ left: 12px; }}
    #btn-toggle-right {{ right: 12px; }}

    /* Controls Styling */
    .section-title {{
      font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748b;
      margin-top: 10px; margin-bottom: 6px; letter-spacing: 0.5px;
    }}
    .rpm-display-box {{
      background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px;
      padding: 10px; text-align: center; margin-bottom: 8px;
    }}
    .rpm-value-large {{
      font-size: 26px; font-weight: 800; color: #2563eb; line-height: 1;
    }}
    .rpm-slider-ctrl {{
      width: 100%; margin: 8px 0; accent-color: #2563eb; cursor: pointer;
    }}
    .btn-grid {{
      display: grid; grid-template-columns: repeat(4, 1fr); gap: 4px; margin-bottom: 8px;
    }}
    .ctrl-btn {{
      background: #f1f5f9; color: #1e293b; border: 1px solid #cbd5e1;
      padding: 5px 4px; border-radius: 6px; font-size: 11px; font-weight: 600;
      cursor: pointer; text-align: center; transition: all 0.15s;
    }}
    .ctrl-btn:hover {{ background: #e2e8f0; border-color: #94a3b8; }}
    .ctrl-btn.active {{
      background: #2563eb; color: #ffffff; border-color: #1d4ed8;
    }}

    /* Individual Jar Cards */
    .jar-card {{
      background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px;
      padding: 8px 10px; margin-bottom: 6px; transition: border-color 0.15s;
      box-shadow: 0 1px 3px rgba(0,0,0,0.03);
    }}
    .jar-card-header {{
      display: flex; justify-content: space-between; align-items: center;
      font-weight: 700; font-size: 11.5px; color: #0f172a; margin-bottom: 4px;
    }}
    .jar-indicator-pill {{
      display: inline-flex; align-items: center; gap: 4px; font-size: 10px;
      padding: 2px 6px; border-radius: 4px; font-weight: 600;
      background: #ffedd5; color: #c2410c;
    }}
    .jar-stat-grid {{
      display: grid; grid-template-columns: 1fr 1fr; gap: 4px; font-size: 10.5px; color: #475569;
    }}
    .jar-stat-item b {{ color: #0f172a; }}

    /* Bottom Dock Toolbar */
    #bottom-ctrls {{
      position: absolute; bottom: 14px; left: 50%; transform: translateX(-50%); z-index: 10;
      background: rgba(255, 255, 255, 0.94); backdrop-filter: blur(8px);
      padding: 6px 12px; border-radius: 30px; border: 1px solid #cbd5e1;
      box-shadow: 0 4px 12px rgba(0,0,0,0.08); display: flex; gap: 6px;
    }}
    .dock-btn {{
      background: #ffffff; color: #334155; border: 1px solid #cbd5e1;
      padding: 5px 10px; border-radius: 20px; font-size: 11px; font-weight: 600; cursor: pointer;
    }}
    .dock-btn:hover {{ background: #f1f5f9; color: #0f172a; }}
    .dock-btn.active {{ background: #0f172a; color: #ffffff; border-color: #0f172a; }}
  </style>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js"></script>
</head>
<body>
  <div id="viewport-container">
    <button class="panel-toggle-btn" id="btn-toggle-left" title="Toggle Hierarchy Tree">📁 Tree</button>
    <button class="panel-toggle-btn" id="btn-toggle-right" title="Toggle Jar Telemetry">📊 Spindles</button>

    <!-- LEFT PANEL: Assembly Hierarchy Tree -->
    <div class="cad-panel" id="left-hierarchy-panel">
      <div class="panel-header">
        <span>📁 Model Hierarchy Tree</span>
        <button class="ctrl-btn" id="btn-close-left" style="padding:2px 6px;">✕</button>
      </div>
      <div class="panel-body">
        <div style="font-size:11px; color:#64748b; margin-bottom:8px;">Toggle checkboxes to show/hide parts:</div>
        
        <div class="tree-node">
          <div class="tree-row">
            <input type="checkbox" class="tree-checkbox" id="chk-root" checked>
            <span class="node-icon">📦</span>
            <strong>Planetary Mill Assembly</strong>
          </div>

          <div class="tree-indent" id="tree-root-children">
            <div class="tree-node">
              <div class="tree-row">
                <input type="checkbox" class="tree-checkbox" id="chk-base" checked>
                <span class="node-icon">🔘</span>
                <span>Base Motor Housing</span>
              </div>
            </div>
            <div class="tree-node">
              <div class="tree-row">
                <input type="checkbox" class="tree-checkbox" id="chk-disc" checked>
                <span class="node-icon">💿</span>
                <span>Sun Carrier Disc</span>
              </div>
            </div>
            <div class="tree-node">
              <div class="tree-row">
                <input type="checkbox" class="tree-checkbox" id="chk-sungear" checked>
                <span class="node-icon">⚙️</span>
                <span>Stationary Sun Gear (Zs)</span>
              </div>
            </div>
            <div class="tree-node">
              <div class="tree-row">
                <input type="checkbox" class="tree-checkbox" id="chk-shaft" checked>
                <span class="node-icon">🔩</span>
                <span>Motor Drive Shaft & Indicator</span>
              </div>
            </div>

            <div class="section-title" style="margin-top:10px;">Planetary Jars</div>
            <div class="tree-node">
              <div class="tree-row">
                <input type="checkbox" class="tree-checkbox" id="chk-all-gears" checked>
                <span class="node-icon">⚙️</span>
                <span>All Planet Gears (Zp)</span>
              </div>
            </div>
            <div class="tree-node">
              <div class="tree-row">
                <input type="checkbox" class="tree-checkbox" id="chk-all-fins" checked>
                <span class="node-icon">🌀</span>
                <span>Annular Cooling Fins (5x)</span>
              </div>
            </div>
            <div class="tree-node">
              <div class="tree-row">
                <input type="checkbox" class="tree-checkbox" id="chk-all-lids" checked>
                <span class="node-icon">🔒</span>
                <span>Clamp Lids & ω Indicators</span>
              </div>
            </div>
            <div class="tree-node">
              <div class="tree-row">
                <input type="checkbox" class="tree-checkbox" id="chk-all-balls" checked>
                <span class="node-icon">⚪</span>
                <span>Grinding Media (Balls)</span>
              </div>
            </div>

            <div class="section-title" style="margin-top:10px;">Individual Jar Spindles</div>
            {"".join([f'''
            <div class="tree-node">
              <div class="tree-row">
                <input type="checkbox" class="tree-checkbox" id="chk-jar-{i}" checked>
                <span class="node-icon">🧪</span>
                <span>Jar #{i+1} (Pos: {i*(360//n_vials)}°)</span>
              </div>
            </div>
            ''' for i in range(n_vials)])}
          </div>
        </div>
      </div>
    </div>

    <!-- RIGHT PANEL: Motor RPM Control & Per-Jar Telemetry Monitor -->
    <div class="cad-panel" id="right-telemetry-panel">
      <div class="panel-header">
        <span>📊 Spindle RPM & Telemetry</span>
        <button class="ctrl-btn" id="btn-close-right" style="padding:2px 6px;">✕</button>
      </div>
      <div class="panel-body">
        <div class="section-title">Drive Motor RPM Control (Ω)</div>
        <div class="rpm-display-box">
          <div style="font-size:11px; color:#64748b;">SUN CARRIER ROTATION</div>
          <div class="rpm-value-large" id="disp-sun-rpm">{sun_rpm_init:.0f} <span style="font-size:14px; font-weight:600; color:#64748b;">RPM</span></div>
          <div style="font-size:11px; color:#475569;" id="disp-sun-rads">{(sun_rpm_init*2*np.pi/60):.1f} rad/s</div>
        </div>

        <input type="range" class="rpm-slider-ctrl" id="slider-rpm" min="100" max="1000" step="25" value="{sun_rpm_init}">

        <div class="btn-grid">
          <button class="ctrl-btn" data-preset-rpm="300">300</button>
          <button class="ctrl-btn active" data-preset-rpm="450">450</button>
          <button class="ctrl-btn" data-preset-rpm="600">600</button>
          <button class="ctrl-btn" data-preset-rpm="800">800</button>
        </div>

        <div class="section-title">Transmission Ratio (k = ω/Ω)</div>
        <div style="display:flex; flex-wrap:wrap; gap:4px; margin-bottom:10px;">
          <button class="ctrl-btn ratio-btn" data-ratio="-1.0">k = -1.0</button>
          <button class="ctrl-btn ratio-btn" data-ratio="-1.5">k = -1.5</button>
          <button class="ctrl-btn ratio-btn active" data-ratio="-2.0">k = -2.0</button>
          <button class="ctrl-btn ratio-btn" data-ratio="-2.5">k = -2.5</button>
          <button class="ctrl-btn ratio-btn" data-ratio="-3.0">k = -3.0</button>
        </div>

        <!-- Gear Teeth & Pitch Diameter Display -->
        <div style="background:#f8fafc; border:1px solid #e2e8f0; border-radius:6px; padding:6px 8px; margin-bottom:8px; font-size:11px;">
          <div style="display:flex; justify-content:space-between; margin-bottom:2px;">
            <span>Sun Gear (Zs):</span>
            <strong id="disp-sun-teeth">40 T (Ø 21.3)</strong>
          </div>
          <div style="display:flex; justify-content:space-between; margin-bottom:2px;">
            <span>Planet Gear (Zp):</span>
            <strong id="disp-planet-teeth">20 T (Ø 10.7)</strong>
          </div>
          <div style="display:flex; justify-content:space-between; color:#16a34a;">
            <span>Pitch Sum (rs + rp):</span>
            <strong id="disp-pitch-sum">{R_sun:.1f} = R_sun (Exact)</strong>
          </div>
        </div>

        <div class="section-title">Individual Jar Spindles Monitor ({n_vials} Jars)</div>
        <div id="jar-cards-container">
          {"".join([f'''
          <div class="jar-card" id="card-jar-{i}">
            <div class="jar-card-header">
              <span>🧪 Jar #{i+1} (Spindle {i*(360//n_vials)}°)</span>
              <span class="jar-indicator-pill">↺ Counter-Spin</span>
            </div>
            <div class="jar-stat-grid">
              <div class="jar-stat-item">Rel Spin (ω): <b id="stat-jar-rel-{i}">-900 RPM</b></div>
              <div class="jar-stat-item">Abs Lab Speed: <b id="stat-jar-abs-{i}">-450 RPM</b></div>
              <div class="jar-stat-item">Wall G-Force: <b id="stat-jar-g-{i}">40.2 G</b></div>
              <div class="jar-stat-item">Tip Speed: <b id="stat-jar-vtip-{i}">4.2 m/s</b></div>
            </div>
          </div>
          ''' for i in range(n_vials)])}
        </div>

        <div class="section-title" style="margin-top:12px;">Kinematic Dynamics Summary</div>
        <div style="background:#f1f5f9; padding:8px 10px; border-radius:8px; font-size:11px;">
          <div style="display:flex; justify-content:space-between; margin-bottom:3px;">
            <span>Effective Centrifugal G-Force:</span>
            <strong id="stat-gforce-val">{self.kin.g_force_sun():.1f} G</strong>
          </div>
          <div style="display:flex; justify-content:space-between; margin-bottom:3px;">
            <span>Estimated Collision Velocity:</span>
            <strong id="stat-vimp-val">2.38 m/s</strong>
          </div>
          <div style="display:flex; justify-content:space-between;">
            <span>Milling Motion Regime:</span>
            <strong id="stat-regime-val" style="color:#2563eb;">Cataracting (Optimal Nano)</strong>
          </div>
        </div>
      </div>
    </div>

    <!-- Bottom Dock Toolbar -->
    <div id="bottom-ctrls">
      <button class="dock-btn" id="btn-toggle-rot">Pause Rotation</button>
      <button class="dock-btn" id="btn-toggle-dir">Reverse Direction (↺ CCW)</button>
      <button class="dock-btn" id="btn-toggle-xray">X-Ray Vials</button>
      <button class="dock-btn active" id="btn-toggle-edges">Black Edges</button>
      <button class="dock-btn" id="btn-reset-cam">Reset View</button>
    </div>

    <div id="canvas-3d"></div>
  </div>

  <script>
    const container = document.getElementById('canvas-3d');
    const width = container.clientWidth || 800;
    const height = container.clientHeight || 640;

    // --- SCENE SETUP (LIGHT MODE) ---
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0xf8fafc);
    scene.fog = new THREE.FogExp2(0xf8fafc, 0.005);

    const camera = new THREE.PerspectiveCamera(45, width / height, 0.1, 1000);
    camera.position.set(40, 48, 62);

    const renderer = new THREE.WebGLRenderer({{ antialias: true, alpha: false }});
    renderer.setSize(width, height);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    container.appendChild(renderer.domElement);

    const controls = new THREE.OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.dampingFactor = 0.06;
    controls.target.set(0, 5, 0);

    // --- LIGHTING ---
    const ambientLight = new THREE.AmbientLight(0xffffff, 0.75);
    scene.add(ambientLight);

    const keyLight = new THREE.DirectionalLight(0xffffff, 0.85);
    keyLight.position.set(45, 70, 40);
    keyLight.castShadow = true;
    scene.add(keyLight);

    const fillLight = new THREE.DirectionalLight(0xe2e8f0, 0.45);
    fillLight.position.set(-40, 30, -30);
    scene.add(fillLight);

    // --- GROUND & CAD GRID ---
    const grid = new THREE.GridHelper(90, 30, 0x94a3b8, 0xcbd5e1);
    grid.position.y = -2.0;
    scene.add(grid);

    // Black edge tracking
    const edgeLines = [];
    const edgeMaterial = new THREE.LineBasicMaterial({{ color: 0x0f172a, linewidth: 1.5 }});

    function addBlackEdges(mesh, thresholdAngle = 26) {{
      const edges = new THREE.EdgesGeometry(mesh.geometry, thresholdAngle);
      const line = new THREE.LineSegments(edges, edgeMaterial);
      mesh.add(line);
      edgeLines.push(line);
      return line;
    }}

    // --- PROCEDURAL INVOLUTE-LIKE SPUR GEAR GENERATOR ---
    function createGearGeometry(pitchRadius, thickness, numTeeth, toothHeight, boreRadius) {{
      const shape = new THREE.Shape();
      const toothAngle = (2 * Math.PI) / numTeeth;
      const rTip = pitchRadius + toothHeight * 0.42;
      const rBase = pitchRadius - toothHeight * 0.52;

      for (let i = 0; i < numTeeth; i++) {{
        const a0 = i * toothAngle;
        const a1 = a0 + toothAngle * 0.16; // root bottom
        const a2 = a0 + toothAngle * 0.32; // flank up
        const a3 = a0 + toothAngle * 0.48; // top crest
        const a4 = a0 + toothAngle * 0.64; // flank down
        const a5 = (i + 1) * toothAngle;   // root bottom

        if (i === 0) shape.moveTo(rBase * Math.cos(a0), rBase * Math.sin(a0));
        else shape.lineTo(rBase * Math.cos(a0), rBase * Math.sin(a0));

        shape.lineTo(rBase * Math.cos(a1), rBase * Math.sin(a1));
        shape.lineTo(rTip * Math.cos(a2), rTip * Math.sin(a2));
        shape.lineTo(rTip * Math.cos(a3), rTip * Math.sin(a3));
        shape.lineTo(rBase * Math.cos(a4), rBase * Math.sin(a4));
        shape.lineTo(rBase * Math.cos(a5), rBase * Math.sin(a5));
      }}
      shape.closePath();

      if (boreRadius > 0) {{
        const hole = new THREE.Path();
        hole.absarc(0, 0, boreRadius, 0, Math.PI * 2, true);
        shape.holes.push(hole);
      }}

      const extrudeSettings = {{
        depth: thickness, bevelEnabled: true, bevelSegments: 1, steps: 1, bevelSize: 0.12, bevelThickness: 0.12
      }};
      const geom = new THREE.ExtrudeGeometry(shape, extrudeSettings);
      geom.center();
      return geom;
    }}

    // --- GEOMETRIC CONSTANTS & ELEVATIONS ---
    const R_s = {R_sun};
    const r_v = {r_vial + 1.0};
    const h_v = {h_vial + 1.5};
    const nVials = {n_vials};

    // Coplanar gear plane elevation
    const gearY = 1.0;
    const gearThickness = 1.8;

    // Carrier disc elevation (sits directly above gears)
    const discY = 2.6;
    const discThickness = 1.6;

    // Vial base elevation (rests on top of carrier disc)
    const vialBaseY = discY + discThickness; // 4.2

    // --- ASSEMBLY GROUPS ---
    const rootAssembly = new THREE.Group();
    scene.add(rootAssembly);

    // 1. Stationary Base & Housing
    const baseGeom = new THREE.CylinderGeometry(R_s + r_v + 5.0, R_s + r_v + 7.0, 4.0, 36);
    const baseMat = new THREE.MeshStandardMaterial({{ color: 0xe2e8f0, roughness: 0.4, metalness: 0.5 }});
    const baseMesh = new THREE.Mesh(baseGeom, baseMat);
    baseMesh.position.y = -2.0;
    rootAssembly.add(baseMesh);
    addBlackEdges(baseMesh);

    // 2. Rotating Carrier Assembly (Rotates around Y at Omega)
    const sunAssembly = new THREE.Group();
    rootAssembly.add(sunAssembly);

    // Sun Carrier Disc
    const discRadius = R_s + r_v + 3.0;
    const discGeom = new THREE.CylinderGeometry(discRadius, discRadius, discThickness, 48);
    const discMat = new THREE.MeshStandardMaterial({{ color: 0xf1f5f9, roughness: 0.3, metalness: 0.55 }});
    const sunDiscMesh = new THREE.Mesh(discGeom, discMat);
    sunDiscMesh.position.y = discY + discThickness / 2;
    sunDiscMesh.receiveShadow = true;
    sunAssembly.add(sunDiscMesh);
    addBlackEdges(sunDiscMesh);

    // Central Motor Drive Shaft & Indicator
    const shaftGroup = new THREE.Group();
    const shaftGeom = new THREE.CylinderGeometry(2.2, 2.2, vialBaseY + 14, 24);
    const shaftMat = new THREE.MeshStandardMaterial({{ color: 0x94a3b8, metalness: 0.8, roughness: 0.25 }});
    const shaftMesh = new THREE.Mesh(shaftGeom, shaftMat);
    shaftMesh.position.y = (vialBaseY + 14) / 2;
    shaftGroup.add(shaftMesh);
    addBlackEdges(shaftMesh);

    const arrowHubGeom = new THREE.CylinderGeometry(2.6, 2.6, 1.5, 20);
    const arrowMat = new THREE.MeshStandardMaterial({{ color: 0x2563eb, metalness: 0.5, roughness: 0.3 }});
    const arrowHub = new THREE.Mesh(arrowHubGeom, arrowMat);
    arrowHub.position.y = vialBaseY + 14 + 1.0;
    shaftGroup.add(arrowHub);
    addBlackEdges(arrowHub);

    const ptrGeom = new THREE.ConeGeometry(1.6, 4.0, 16);
    const ptrMesh = new THREE.Mesh(ptrGeom, arrowMat);
    ptrMesh.rotation.z = -Math.PI / 2;
    ptrMesh.position.set(4.2, vialBaseY + 14 + 1.0, 0);
    shaftGroup.add(ptrMesh);
    addBlackEdges(ptrMesh);
    sunAssembly.add(shaftGroup);

    // Materials
    const sunGearMat = new THREE.MeshStandardMaterial({{ color: 0xd97706, roughness: 0.35, metalness: 0.7 }});
    const planetGearMat = new THREE.MeshStandardMaterial({{ color: 0x64748b, roughness: 0.35, metalness: 0.6 }});
    const finMat = new THREE.MeshStandardMaterial({{ color: 0xf8fafc, roughness: 0.3, metalness: 0.45 }});
    const clampLidMat = new THREE.MeshStandardMaterial({{ color: 0x2563eb, roughness: 0.35, metalness: 0.6 }});
    const jarIndicatorMat = new THREE.MeshStandardMaterial({{ color: 0xea580c, roughness: 0.25, metalness: 0.4 }});

    // 3. Planetary Vials & Spindle Assemblies
    const vials = [];
    const vialMaterials = [];
    const planetGearMeshes = [];
    const finMeshes = [];
    const lidMeshes = [];
    const ballMeshes = [];
    let sunGearMesh = null;

    let currentK = {k_init};
    let currentSunRPM = {sun_rpm_init};

    for (let i = 0; i < nVials; i++) {{
      const angle = (i * 2 * Math.PI) / nVials;
      const vialGroup = new THREE.Group();
      vialGroup.position.set(R_s * Math.cos(angle), 0, R_s * Math.sin(angle));

      // Spindle shaft connecting gear to vial through carrier disc
      const spindleShaftGeom = new THREE.CylinderGeometry(1.2, 1.2, vialBaseY - gearY + 1.0, 16);
      const spindleShaft = new THREE.Mesh(spindleShaftGeom, shaftMat);
      spindleShaft.position.y = gearY + (vialBaseY - gearY) / 2;
      vialGroup.add(spindleShaft);
      addBlackEdges(spindleShaft);

      // Vial Body (rests on carrier disc)
      const vGeom = new THREE.CylinderGeometry(r_v, r_v, h_v, 32);
      const vMat = new THREE.MeshStandardMaterial({{
        color: 0xf8fafc, roughness: 0.3, metalness: 0.5, transparent: false, opacity: 1.0
      }});
      vialMaterials.push(vMat);
      const vMesh = new THREE.Mesh(vGeom, vMat);
      vMesh.position.y = vialBaseY + h_v / 2;
      vMesh.castShadow = true;
      vialGroup.add(vMesh);
      addBlackEdges(vMesh);

      // Annular Cooling Fins (5 ribs)
      const numFins = 5;
      const finSpacing = h_v / (numFins + 1);
      for (let f = 1; f <= numFins; f++) {{
        const finGeom = new THREE.CylinderGeometry(r_v + 1.8, r_v + 1.8, 0.45, 32);
        const finMesh = new THREE.Mesh(finGeom, finMat);
        finMesh.position.y = vialBaseY + f * finSpacing;
        vialGroup.add(finMesh);
        addBlackEdges(finMesh);
        finMeshes.push(finMesh);
      }}

      // Vial Clamp Lid & Knob
      const lidGroup = new THREE.Group();
      const lidGeom = new THREE.CylinderGeometry(r_v * 1.1, r_v * 1.1, 2.2, 32);
      const lidMesh = new THREE.Mesh(lidGeom, clampLidMat);
      lidMesh.position.y = vialBaseY + h_v + 1.1;
      lidGroup.add(lidMesh);
      addBlackEdges(lidMesh);

      const knobGeom = new THREE.CylinderGeometry(2.5, 2.5, 1.8, 20);
      const knobMesh = new THREE.Mesh(knobGeom, clampLidMat);
      knobMesh.position.y = vialBaseY + h_v + 2.8;
      lidGroup.add(knobMesh);
      addBlackEdges(knobMesh);

      // Rotational Direction Indicator Arrow on Lid Top
      const barGeom = new THREE.BoxGeometry(r_v * 1.6, 0.5, 0.8);
      const barMesh = new THREE.Mesh(barGeom, jarIndicatorMat);
      barMesh.position.y = vialBaseY + h_v + 3.8;
      lidGroup.add(barMesh);
      addBlackEdges(barMesh);

      const arrowHeadGeom = new THREE.ConeGeometry(1.2, 2.5, 12);
      const arrowHead = new THREE.Mesh(arrowHeadGeom, jarIndicatorMat);
      arrowHead.rotation.z = -Math.PI / 2;
      arrowHead.position.set((r_v * 1.6) / 2 + 1.0, vialBaseY + h_v + 3.8, 0);
      lidGroup.add(arrowHead);
      addBlackEdges(arrowHead);

      vialGroup.add(lidGroup);
      lidMeshes.push(lidGroup);

      // Grinding Balls inside
      const ballMat = new THREE.MeshStandardMaterial({{ color: 0xf59e0b, roughness: 0.2, metalness: 0.85 }});
      const bGeom = new THREE.SphereGeometry(1.1, 16, 16);
      for (let b = 0; b < 6; b++) {{
        const bMesh = new THREE.Mesh(bGeom, ballMat);
        bMesh.position.set((Math.random() - 0.5) * r_v * 1.2, vialBaseY + 2.0 + b * 1.5, (Math.random() - 0.5) * r_v * 1.2);
        vialGroup.add(bMesh);
        ballMeshes.push(bMesh);
      }}

      // Group holding the planet gear at gearY
      const gearHolder = new THREE.Group();
      gearHolder.position.y = gearY;
      vialGroup.add(gearHolder);

      sunAssembly.add(vialGroup);
      vials.push({{ group: vialGroup, gearHolder: gearHolder, angle: angle }});
    }}

    // --- MATHEMATICALLY EXACT GEAR BUILDER & SIZER ---
    function rebuildGears(k) {{
      const kAbs = Math.abs(k);
      const Z_p = 20;
      const Z_s = Math.round(kAbs * Z_p);

      // Exact pitch radii satisfying r_sun + r_planet = R_s
      const r_planet = R_s * (Z_p / (Z_s + Z_p));
      const r_sun = R_s * (Z_s / (Z_s + Z_p));
      const m = (2.0 * R_s) / (Z_s + Z_p);
      const toothHeight = 1.8 * m;

      // 1. Rebuild Stationary Central Sun Gear anchored to rootAssembly (Base Frame)
      if (sunGearMesh) {{
        rootAssembly.remove(sunGearMesh);
        sunGearMesh.geometry.dispose();
      }}
      const sunGeom = createGearGeometry(r_sun, gearThickness, Z_s, toothHeight, 2.8);
      sunGearMesh = new THREE.Mesh(sunGeom, sunGearMat);
      sunGearMesh.rotation.x = Math.PI / 2;
      sunGearMesh.position.set(0, gearY, 0);
      rootAssembly.add(sunGearMesh); // ANCHORED TO STATIONARY BASE, NEVER ROTATES!
      addBlackEdges(sunGearMesh, 30);

      // 2. Rebuild All Coplanar Planet Gears at exact gearY
      for (let i = 0; i < nVials; i++) {{
        if (planetGearMeshes[i]) {{
          vials[i].gearHolder.remove(planetGearMeshes[i]);
          planetGearMeshes[i].geometry.dispose();
        }}
        const pGeom = createGearGeometry(r_planet, gearThickness, Z_p, toothHeight, 1.4);
        const pGear = new THREE.Mesh(pGeom, planetGearMat);
        pGear.rotation.x = Math.PI / 2;
        pGear.position.set(0, 0, 0);
        // Phase align tooth space facing sun gear
        pGear.rotation.z = Math.PI / Z_p;
        vials[i].gearHolder.add(pGear);
        addBlackEdges(pGear, 30);
        planetGearMeshes[i] = pGear;
      }}

      // Update Pitch Displays
      document.getElementById('disp-sun-teeth').textContent = `${{Z_s}} T (Ø ${{(2 * r_sun).toFixed(1)}})`;
      document.getElementById('disp-planet-teeth').textContent = `${{Z_p}} T (Ø ${{(2 * r_planet).toFixed(1)}})`;
      document.getElementById('disp-pitch-sum').textContent = `${{(r_sun + r_planet).toFixed(1)}} = R_sun (Exact)`;
    }}

    // --- TELEMETRY & DYNAMICS CONTROLLER ---
    function updateDynamics(sunRPM, k) {{
      currentSunRPM = sunRPM;
      currentK = k;
      const kAbs = Math.abs(k);

      // Rebuild and resize gears to exact pitch circles
      rebuildGears(k);

      // Update Sun Displays
      document.getElementById('disp-sun-rpm').innerHTML = `${{Math.round(sunRPM)}} <span style="font-size:14px; font-weight:600; color:#64748b;">RPM</span>`;
      document.getElementById('disp-sun-rads').textContent = `${{(sunRPM * 2 * Math.PI / 60).toFixed(1)}} rad/s`;

      // Centrifugal G-Force
      const omega_sun = (sunRPM * 2 * Math.PI) / 60.0;
      const gSun = (Math.pow(omega_sun, 2) * {self.geom.sun_radius_m}) / 9.80665;
      document.getElementById('stat-gforce-val').textContent = `${{gSun.toFixed(1)}} G`;

      // Impact Velocity
      const vImp = omega_sun * {self.geom.sun_radius_m} * Math.sqrt(Math.max(0.1, 1.0 + Math.pow(k, 2)*Math.pow({self.geom.vial_radius_m/self.geom.sun_radius_m}, 2) - 2*kAbs*({self.geom.vial_radius_m/self.geom.sun_radius_m}))) * 0.72;
      document.getElementById('stat-vimp-val').textContent = `${{vImp.toFixed(2)}} m/s`;

      // Regime Badge
      const regimeEl = document.getElementById('stat-regime-val');
      if (kAbs < 1.2) {{
        regimeEl.textContent = "Cascading (Attrition)";
        regimeEl.style.color = "#d97706";
      }} else if (kAbs <= 2.6) {{
        regimeEl.textContent = "Cataracting (Optimal Nano)";
        regimeEl.style.color = "#2563eb";
      }} else {{
        regimeEl.textContent = "Centrifuging Warning";
        regimeEl.style.color = "#dc2626";
      }}

      // Update Individual Jar Cards
      const speedRatio = Math.abs(k);
      const jarRelRPM = speedRatio * sunRPM;
      const jarAbsRPM = sunRPM * (1.0 + speedRatio);
      const omega_vial = (jarRelRPM * 2 * Math.PI) / 60.0;
      const gWall = (Math.pow(omega_vial, 2) * {self.geom.vial_radius_m}) / 9.80665;
      const vTip = Math.abs(omega_vial * {self.geom.vial_radius_m});

      for (let i = 0; i < nVials; i++) {{
        const relEl = document.getElementById(`stat-jar-rel-${{i}}`);
        const absEl = document.getElementById(`stat-jar-abs-${{i}}`);
        const gEl = document.getElementById(`stat-jar-g-${{i}}`);
        const vEl = document.getElementById(`stat-jar-vtip-${{i}}`);

        if (relEl) relEl.textContent = `+${{Math.round(jarRelRPM)}} RPM`;
        if (absEl) absEl.textContent = `+${{Math.round(jarAbsRPM)}} RPM`;
        if (gEl) gEl.textContent = `${{gWall.toFixed(1)}} G`;
        if (vEl) vEl.textContent = `${{vTip.toFixed(2)}} m/s`;
      }}
    }}

    // RPM Slider
    const sliderRPM = document.getElementById('slider-rpm');
    sliderRPM.addEventListener('input', (e) => {{
      const val = parseFloat(e.target.value);
      updateDynamics(val, currentK);
      document.querySelectorAll('[data-preset-rpm]').forEach(b => {{
        b.classList.toggle('active', parseFloat(b.getAttribute('data-preset-rpm')) === val);
      }});
    }});

    // Preset RPM Buttons
    document.querySelectorAll('[data-preset-rpm]').forEach(btn => {{
      btn.addEventListener('click', () => {{
        const val = parseFloat(btn.getAttribute('data-preset-rpm'));
        sliderRPM.value = val;
        document.querySelectorAll('[data-preset-rpm]').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        updateDynamics(val, currentK);
      }});
    }});

    // Gear Ratio Buttons
    const ratioBtns = document.querySelectorAll('.ratio-btn');
    ratioBtns.forEach(btn => {{
      btn.addEventListener('click', () => {{
        ratioBtns.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        const k = parseFloat(btn.getAttribute('data-ratio'));
        updateDynamics(currentSunRPM, k);
      }});
    }});

    // --- HIERARCHY TREE CHECKBOXES ---
    document.getElementById('chk-root').addEventListener('change', (e) => {{
      rootAssembly.visible = e.target.checked;
    }});
    document.getElementById('chk-base').addEventListener('change', (e) => {{
      baseMesh.visible = e.target.checked;
    }});
    document.getElementById('chk-disc').addEventListener('change', (e) => {{
      sunDiscMesh.visible = e.target.checked;
    }});
    document.getElementById('chk-sungear').addEventListener('change', (e) => {{
      if (sunGearMesh) sunGearMesh.visible = e.target.checked;
    }});
    document.getElementById('chk-shaft').addEventListener('change', (e) => {{
      shaftGroup.visible = e.target.checked;
    }});
    document.getElementById('chk-all-gears').addEventListener('change', (e) => {{
      planetGearMeshes.forEach(m => m.visible = e.target.checked);
    }});
    document.getElementById('chk-all-fins').addEventListener('change', (e) => {{
      finMeshes.forEach(m => m.visible = e.target.checked);
    }});
    document.getElementById('chk-all-lids').addEventListener('change', (e) => {{
      lidMeshes.forEach(m => m.visible = e.target.checked);
    }});
    document.getElementById('chk-all-balls').addEventListener('change', (e) => {{
      ballMeshes.forEach(m => m.visible = e.target.checked);
    }});

    // Individual Jar Checkboxes
    for (let i = 0; i < nVials; i++) {{
      const chk = document.getElementById(`chk-jar-${{i}}`);
      if (chk) {{
        chk.addEventListener('change', (e) => {{
          vials[i].group.visible = e.target.checked;
          const card = document.getElementById(`card-jar-${{i}}`);
          if (card) card.style.opacity = e.target.checked ? "1.0" : "0.4";
        }});
      }}
    }}

    // --- PANEL COLLAPSE / EXPAND ---
    const leftPanel = document.getElementById('left-hierarchy-panel');
    const rightPanel = document.getElementById('right-telemetry-panel');
    const btnToggleLeft = document.getElementById('btn-toggle-left');
    const btnToggleRight = document.getElementById('btn-toggle-right');

    function toggleLeft() {{
      leftPanel.classList.toggle('collapsed');
      btnToggleLeft.style.display = leftPanel.classList.contains('collapsed') ? 'block' : 'none';
    }}
    function toggleRight() {{
      rightPanel.classList.toggle('collapsed');
      btnToggleRight.style.display = rightPanel.classList.contains('collapsed') ? 'block' : 'none';
    }}

    document.getElementById('btn-close-left').addEventListener('click', toggleLeft);
    btnToggleLeft.addEventListener('click', toggleLeft);
    btnToggleLeft.style.display = 'none';

    document.getElementById('btn-close-right').addEventListener('click', toggleRight);
    btnToggleRight.addEventListener('click', toggleRight);
    btnToggleRight.style.display = 'none';

    // --- DISPLAY CONTROLS ---
    let isRotating = true;
    let isXray = false;
    let showEdges = true;

    document.getElementById('btn-toggle-rot').addEventListener('click', (e) => {{
      isRotating = !isRotating;
      e.target.textContent = isRotating ? "Pause Rotation" : "Resume Rotation";
      e.target.classList.toggle('active', !isRotating);
    }});

    document.getElementById('btn-toggle-xray').addEventListener('click', (e) => {{
      isXray = !isXray;
      e.target.classList.toggle('active', isXray);
      vialMaterials.forEach(m => {{
        m.transparent = isXray;
        m.opacity = isXray ? 0.38 : 1.0;
      }});
    }});

    document.getElementById('btn-toggle-edges').addEventListener('click', (e) => {{
      showEdges = !showEdges;
      e.target.classList.toggle('active', showEdges);
      edgeLines.forEach(l => l.visible = showEdges);
    }});

    document.getElementById('btn-reset-cam').addEventListener('click', () => {{
      camera.position.set(40, 48, 62);
      controls.target.set(0, 5, 0);
    }});

    // Reverse Direction Button
    let driveDir = 1.0;
    const btnToggleDir = document.getElementById('btn-toggle-dir');
    if (btnToggleDir) {{
      btnToggleDir.addEventListener('click', (e) => {{
        driveDir *= -1.0;
        e.target.textContent = driveDir > 0 ? "Reverse Direction (↺ CCW)" : "Normal Direction (↻ CW)";
        e.target.classList.toggle('active', driveDir < 0);
      }});
    }}

    window.addEventListener('resize', () => {{
      const w = container.clientWidth;
      const h = container.clientHeight;
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
      renderer.setSize(w, h);
    }});

    // --- ANIMATION LOOP ---
    function animate() {{
      requestAnimationFrame(animate);
      if (isRotating) {{
        // Carrier / Sun disk rotation step
        const currentOmega = driveDir * (currentSunRPM / 450.0) * 0.012;
        sunAssembly.rotation.y += currentOmega;

        // Planet gears pure rolling kinematics on stationary central sun gear:
        // As the carrier rotates by dTheta, the planet gear meshing on the stationary sun gear
        // rolls along the sun gear pitch circle with zero slip at the contact point:
        // v_contact = v_carrier - omega_rel * r_planet = 0 ==> omega_rel = +(Zs / Zp) * Omega = +|k| * Omega.
        // Therefore, relative to the carrier disc, the jar spindle rotates in the positive direction:
        const speedRatio = Math.abs(currentK);
        const vialSpinSpeed = speedRatio * currentOmega;
        vials.forEach(v => {{
          v.group.rotation.y += vialSpinSpeed;
        }});
      }}
      controls.update();
      renderer.render(scene, camera);
    }}
    animate();

    // Initial dynamics and gear sync
    updateDynamics(currentSunRPM, currentK);
  </script>
</body>
</html>
"""
        return html_template
